# Generated by Django 5.1.2 on 2024-10-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_token_updated'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('group', 'value'), name='unique_in_group'),
        ),
    ]
